#! /bin/bash

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Tokenized_Corpora/wiki-tokenized.de.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Dictionaries-Frequencies/wiki-dic.de.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Corpora/wiki-tokenized-transformed.de.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Dictionary/wiki-dic-transformed.de.txt

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Tokenized_Corpora/wiki-tokenized.en.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Dictionaries-Frequencies/wiki-dic.en.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Corpora/wiki-tokenized-transformed.en.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Dictionary/wiki-dic-transformed.en.txt

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Tokenized_Corpora/wiki-tokenized.es.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Dictionaries-Frequencies/wiki-dic.es.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Corpora/wiki-tokenized-transformed.es.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Dictionary/wiki-dic-transformed.es.txt

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Tokenized_Corpora/wiki-tokenized.fr.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Dictionaries-Frequencies/wiki-dic.fr.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Corpora/wiki-tokenized-transformed.fr.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Dictionary/wiki-dic-transformed.fr.txt

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Tokenized_Corpora/wiki-tokenized.it.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Dictionaries-Frequencies/wiki-dic.it.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Corpora/wiki-tokenized-transformed.it.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Dictionary/wiki-dic-transformed.it.txt

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Tokenized_Corpora/wiki-tokenized.nl.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Dictionaries-Frequencies/wiki-dic.nl.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Corpora/wiki-tokenized-transformed.nl.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Dictionary/wiki-dic-transformed.nl.txt

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Tokenized_Corpora/wiki-tokenized.ru.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Dictionaries-Frequencies/wiki-dic.ru.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Corpora/wiki-tokenized-transformed.ru.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Dictionary/wiki-dic-transformed.ru.txt

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Tokenized_Corpora/wiki-tokenized.el.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Dictionaries-Frequencies/wiki-dic.el.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Corpora/wiki-tokenized-transformed.el.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/FastText_Corpora/data/wikimedia/20191203/Transformed_Dictionary/wiki-dic-transformed.el.txt

python3.7 TransformTokenizedCorpusToIndexes.py /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/Japanese/Tokenized_Corpus/wiki-tokenized.ja.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/Japanese/DIctionary_Freq/wiki-dic.ja.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/Japanese/Transformed_Corpus/wiki-tokenized-transformed.ja.txt /home/akabiri/arman.kabiri94@gmail.com/NLP_Stuff/Embeddings-Corpora--IG--/Japanese/Transformed_Dictionary/wiki-dic-transformed.ja.txt
